version: '3'
services:
  frases:
    image: frases
    build: ./dockerfiles/servicos/
    hostname: frases
    expose:
      - '5000'
    volumes:
      - './frases:/servico'
    command: python3 servico.py
    networks:
      papironet:
        ipv4_address: 172.29.1.1
  bancodados:
    image: mysql
    hostname: bancodados
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      papironet:
        ipv4_address: 172.29.1.2
  arquivos:
    image: arquivos
    build: ./dockerfiles/nginx
    volumes:
      - './imagens:/usr/share/nginx/html'
    hostname: arquivos
    expose:
      - '80'
    networks:
      papironet:
        ipv4_address: 172.29.1.3
networks:
  papironet:
    ipam:
      driver: default
      config:
        - subnet: 172.29.1.0/16
